version: '3.4'

services:
  app: &app
    image: ruby:latest
    environment:
      - BUNDLE_PATH=/bundle
      - BUNDLE_CONFIG=/app/.bundle/config

      - DATABASE_URL=postgresql://postgres@postgres/yabeda-delayed_job
    working_dir: /app
    volumes:
      - ..:/gem:cached
      - .:/app:cached
      - bundler_data:/bundle
    tmpfs:
      - /tmp
    depends_on:
      - postgres

  enqueuer:
    <<: *app
    command: bundle exec ./enqueuer.rb

  delayed_job:
    <<: *app
    command: bundle exec ./delayed_job.rb
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=yabeda-delayed_job

  prometheus:
    image: prom/prometheus:v2.25.2
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    depends_on:
      - enqueuer
      - delayed_job
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.4.3
    depends_on:
      - prometheus    
    ports:
      - 9091:9091/tcp
    environment:
      GF_SECURITY_ADMIN_USER: admin@admin.ru
      GF_SECURITY_ADMIN_PASSWORD: "12345678"
    volumes: 
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    user: "104"


volumes:
  bundler_data:
  postgres:
  grafana-data:

