global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'enqueuer'
  scheme: http
  metrics_path: '/metrics'
  static_configs:
    - targets:
      - 'enqueuer:9394'
- job_name: 'delayed_job'
  scheme: http
  metrics_path: '/metrics'
  static_configs:
    - targets:
      - 'delayed_job:9394'

